name: tusabitacoraapp
description: "A new Flutter project."
publish_to: 'none' 

version: 1.9.1

environment:
  #sdk: ">=2.16.1 <3.24.5"
   sdk: ">=2.16.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  after_layout: ^1.2.0
  ai_barcode_scanner: ^6.0.1
  animate_do: ^3.0.2
  animated_snack_bar: ^0.3.1
  app_popup_menu: ^1.0.0
  awesome_top_snackbar: ^0.0.3
  cached_network_image: ^3.4.0
  calendar_date_picker2: ^1.1.8
  change_app_package_name: ^1.4.0
  cloudflare: ^3.2.1+1
  cloud_firestore: ^4.17.5
  connectivity_plus: ^6.1.4
  cupertino_calendar_picker: ^2.2.4
  cupertino_icons: ^1.0.8
  custom_refresh_indicator: ^2.2.1
  data_table_2: ^2.2.1
  device_info_plus: ^9.1.2
  dio: ^5.3.2
  dropdown_button2: ^2.3.9
  easy_splash_screen: ^1.0.4
  email_validator: ^2.1.17
  emoji_picker_flutter: ^2.2.0
  firebase_core: ^2.17.1
  firebase_messaging: ^14.8.1
  fl_chart: ^0.46.0
  flat_list: ^0.1.14
  fleather: ^1.19.0
  flutter_cache_manager: ^3.3.0
  flutter_cupertino_datetime_picker: ^3.0.0
  flutter_easyloading: ^3.0.5
  flutter_expandable_fab: ^2.3.0
  flutter_icon_snackbar: ^1.1.4
  flutter_image_slideshow: ^0.1.6
  #flutter_launcher_icons: ^0.14.3
  flutter_launcher_icons: ^0.11.0
  flutter_local_notifications: ^19.0.0
  flutter_pdfview: ^1.3.4
  flutter_svg: ^1.0.3
  flutter_widget_from_html: ^0.9.1
  font_awesome_flutter: ^10.7.0
  ftpconnect: ^2.0.7
  future_progress_dialog: ^0.2.1
  google_fonts: ^5.0.0
  google_nav_bar: ^5.0.6
  googleapis_auth: ^1.6.0
  http: ^1.0.0
  html_editor_enhanced: ^2.6.0
  image_picker: ^1.1.2
  intl: ^0.19.0
  mssql_connection: ^2.0.1
  package_info_plus: ^8.1.1
  page_view_dot_indicator: ^2.3.0
  path: ^1.9.0
  path_provider: ^2.1.3
  permission_handler: ^10.2.0
  photo_view: ^0.15.0
  provider: ^6.0.2
  quill_json_to_html: ^1.0.1
  shared_preferences: ^2.5.2
  signature: ^5.3.0
  smart_snackbars: ^1.0.0
  sqflite: ^2.4.1
  toggle_switch: ^2.3.0
  url_launcher: ^6.3.1
  win32: ^5.8.0
  flutter_localizations:
    sdk: flutter
  easy_image_viewer: ^1.5.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/logoatm12.png"
  adaptive_icon_background: "assets/icon/logoatm12.png"

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icon/